apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patchpilot.fullname" . }}-config
  labels: {{ include "patchpilot.labels" . | nindent 4 }}
data:
  KEYCLOAK_URL:       {{ .Values.config.keycloakUrl | quote }}
  KEYCLOAK_REALM:     {{ .Values.config.keycloakRealm | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.config.keycloakClientId | quote }}
  TRIVY_SERVER_URL:   {{ tpl .Values.config.trivyServerUrl . | quote }}
  REDIS_URL:          {{ tpl .Values.config.redisUrl . | quote }}
