"""initial_schema

Revision ID: 9f49298ff25b
Revises:
Create Date: 2026-06-16 23:37:54.227053

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f49298ff25b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("keycloak_sub", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "EDITOR", "VIEWER", name="userrole"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_keycloak_sub"), "users", ["keycloak_sub"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=True),
        sa.Column("metadata_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "registries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ECR", "ACR", "DOCKERHUB", "GAR", "GENERIC_OCI", name="registrytype"),
            nullable=False,
        ),
        sa.Column("registry_url", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("auth_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("auth_dek_enc", sa.LargeBinary(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_registries_team_id"), "registries", ["team_id"], unique=False)
    op.create_table(
        "images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("registry_id", sa.UUID(), nullable=False),
        sa.Column("repository", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("last_digest", sa.String(), nullable=True),
        sa.Column("service_type", sa.Enum("UI", "BACKEND", name="servicetype"), nullable=False),
        sa.Column("base_dockerfile_path", sa.String(), nullable=False),
        sa.Column("app_dockerfile_path", sa.String(), nullable=False),
        sa.Column("gitlab_project_id", sa.String(), nullable=False),
        sa.Column("gitlab_default_branch", sa.String(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["registry_id"],
            ["registries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_team_id"), "images", ["team_id"], unique=False)
    op.create_table(
        "scans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("triggered_by", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "SUCCEEDED", "FAILED", name="scanstatus"),
            nullable=False,
        ),
        sa.Column("trivy_version", sa.String(), nullable=True),
        sa.Column("db_version", sa.String(), nullable=True),
        sa.Column("image_digest", sa.String(), nullable=True),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("finished_at", sa.String(), nullable=True),
        sa.Column("summary_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_report_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("vuln_id", sa.String(), nullable=False),
        sa.Column("pkg_name", sa.String(), nullable=False),
        sa.Column("installed_version", sa.String(), nullable=False),
        sa.Column("fixed_version", sa.String(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN", name="severity"),
            nullable=False,
        ),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("primary_url", sa.String(), nullable=True),
        sa.Column("is_fixable", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "SELECTED", "MR_RAISED", "IGNORED", "RESOLVED", name="findingstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merge_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("mr_type", sa.Enum("FEATURE", "HOTFIX", name="mrtype"), nullable=False),
        sa.Column(
            "target_kind",
            sa.Enum("BASE_DOCKERFILE", "APP_DOCKERFILE", name="mrtargetkind"),
            nullable=False,
        ),
        sa.Column("gitlab_project_id", sa.String(), nullable=False),
        sa.Column("gitlab_mr_iid", sa.Integer(), nullable=True),
        sa.Column("gitlab_mr_url", sa.String(), nullable=True),
        sa.Column("gitlab_pipeline_id", sa.Integer(), nullable=True),
        sa.Column(
            "pipeline_status",
            sa.Enum("PENDING", "RUNNING", "PASSED", "FAILED", "UNKNOWN", name="pipelinestatus"),
            nullable=True,
        ),
        sa.Column("source_branch", sa.String(), nullable=True),
        sa.Column("target_branch", sa.String(), nullable=False),
        sa.Column(
            "state", sa.Enum("OPENED", "MERGED", "CLOSED", "FAILED", name="mrstate"), nullable=False
        ),
        sa.Column("finding_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("image_digest", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("merge_requests")
    op.drop_table("findings")
    op.drop_table("scans")
    op.drop_index(op.f("ix_images_team_id"), table_name="images")
    op.drop_table("images")
    op.drop_index(op.f("ix_registries_team_id"), table_name="registries")
    op.drop_table("registries")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_keycloak_sub"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
